#!/usr/bin/awk -f
#------------------------------------------------------------------------------#
#                            Programmed By Liz                                 #
#------------------------------------------------------------------------------#
# acronym expansion
# using regular expressions
# RSTART & RLENGTH generated by match()
#===============================================================================
BEGIN {
   fil=ENVIRON["HOME"]"/data/acr-sub.dat"       # load acronym expansion array
   while((getline < fil))
   {
      split($0,a,"\t")                          # split line -> array
      acro[a[1]]=a[2]                           # use acronym as index
   }
}
#===============================================================================
{
   p=""                                         # print build string
   for(i=1;i<=NF;i++)                           # scan words
   {
      if(match($i,/[A-Z]{2,}/))                 # acronym = 2 or more caps
      {
         s=substr($i,RSTART,RLENGTH)            # if acronym has punctuation
         p=p sprintf("%s (%s) ",$i,acro[s])     # acronym (expansion)
      }
      else                                      # normal word
         p=p sprintf("%s ",$i)
   }
   sub(/ $/,"",p)                               # remove trailing space
   print p                                      # print line
}
#===============================================================================
END {
}
#===============================================================================
# functions
#-------------------------------------------------------------------------------
#===============================================================================
